### ISSUE TITLE
riot is not a function

### ISSUE THREAD

**Issue by joke1196** [e-jigsaw/gulp-riot#122]
I have been using riot for the past few months and there was no error until this morning (8:30 CET) my riot build fails with the error:
```
[08:26:56] Using gulpfile /builds/ui_src/gulpfile.js
[08:26:56] Starting 'build'...
[08:26:56] 'build' errored after 11 ms
[08:26:56] TypeError: riot is not a function
    at Gulp.<anonymous> (/builds/ui_src/gulpfile.js:17:31)
    at module.exports (/build/ui_src/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/builds/ui_src/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/builds/ui_src/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/builds/ui_src/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp-cli/lib/versioned/^3.7.0/index.js:72:20
    at process._tickCallback (internal/process/next_tick.js:150:11)
```
Here is my gulpfile :
```
const gulp = require('gulp'),
    concat = require('gulp-concat'),
    riot = require('gulp-riot'),
    gulpif = require('gulp-if'),
    webserver = require('gulp-webserver'),
    minify = require('gulp-minify');

gulp.task('build', function () {
    gulp.src(['src/js/lib/*.js',
            'src/js/RiotPolice.js',
            'src/js/RiotStore.js',
            'src/js/store/*.js',
            'src/tag/**/*.tag',
            'src/js/AppConfig.js',
            'src/js/App.js'
        ])
        .pipe(gulpif("*.tag", riot()))
        .pipe(concat('bundle.js'))
        /*.pipe(minify({
            ext:{min:'.min.js'}
        }))*/
        .pipe(gulp.dest('../ui/'));

    gulp.src('src/index.html').pipe(gulp.dest('../ui/'))
    gulp.src('src/img/**/*.*').pipe(gulp.dest('../ui/img/'))
});
```
I am using node v8.9.4 & npm v5.6.0.
I tried to see what was causing the problem and figured out that when importing: `const riot = require('gulp-riot').default` everything would work properly. So maybe there could be something wrong with the way the riot function is exported. Or do I have to use Babel? Because until now it worked perfectly with the `require` keyword, without Babel.

**Comment by e-jigsaw** [comment]
@joke1196 Thank you for reporting. I just published `1.1.4` . Can you try this one?

**Comment by joke1196** [comment]
@e-jigsaw Perfect! It works like a charm! Thanks a lot for the fast response!

**Comment by e-jigsaw** [comment]
np :)
